### ISSUE TITLE
Cou you please share the training data?

### ISSUE THREAD

**Issue by lohas821019** [zyx1121/mmwave-gesture-recognition#1]
Hi , zyx1121
Cou you please share the training data?
I want to know what's your training set type,  i want to add more gesture ,  please

thanks

**Comment by zyx1121** [comment]
Sure, now you can download and extract `records/records.zip` to `records/*.npy` to use.

Additionally, you can use the command `record [gesture] [times]` to record gestures and generate gesture files.

Thanks
